server:
  port: 8081
spring:
  application:
    name: cloud-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.130.186:3506/heima?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root!@#123
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 122.51.209.146
    username: cloud
    password: cloud
    virtual-host: /cloud
    template:
      exchange: cloud.item.exchange
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
        max-attempts: 3
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}