server:
  port: 8085
spring:
  application:
    name: cloud-user
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    host: 122.51.209.146
    port: 6379
  rabbitmq:
    username: cloud
    password: cloud
    virtual-host: /cloud
    host: 122.51.209.146
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.wkdtech.user.entity